In [6]:
import pandas as pd 
ca= pd.read_csv('data/happiness_data_ca.txt')
mx= pd.read_csv('data/happiness_data_mx.txt')
us= pd.read_csv('data/happiness_data_us.txt')
cr= pd.read_csv('data/happiness_data_cr.txt')

In [7]:
ca.head(2)

,nombre del país,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Costa Rica,2006,7.082465,0.936938,0.882420,68.559998
1,Costa Rica,2007,7.432132,0.917678,0.922736,68.720001

In [8]:
mx.head(2)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Mexico,2005,6.580658,0.902808,0.813745,64.400002
1,Mexico,2007,6.525378,0.878806,0.670430,64.680000

In [ ]:

us.head(2)
cr.head(2)